version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
# .env의 값을 바로 이용할 수 없어서 이렇게 사용
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${HOME}/data/postgre:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: nginx_container
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${HOME}/data/staticfiles:/app/staticfiles:ro
    depends_on:
      - transcendence

  transcendence:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transcendence_container
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    volumes:
      - ${HOME}/data/staticfiles:/app/staticfiles
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis