version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${HOME}/data/postgre:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_container
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile2
    container_name: nginx_container
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/static:/app/static:ro
    depends_on:
      - transcendence

  transcendence:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transcendence_container
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    volumes:
      - ${PWD}/static:/app/static
    depends_on:
      - postgres
      - redis