version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: ft_transcendence
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - transcendence

  transcendence:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transcendence_container
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 ft_transcendence.asgi:application"
    environment:
      APP_SECRET_KEY: your_secret_app_key_here
      APP_EMAIL: your_email@example.com
      DATABASE_URL: postgres://admin:admin@postgres:5432/ft_transcendence
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DJANGO_SETTINGS_MODULE: ft_transcendence.settings
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
