# Generated by Django 4.2 on 2024-10-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('tournament', 'Tournament')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
